# Generated by Django 4.1.2 on 2022-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
